<?php
/**
 * Copyright © Refactored Group (https://www.refactored.group)
 * @copyright Copyright © 2022. All rights reserved.
 */
/**
 * Load Dealers PopUp UI Component
 *
 * @var $block \RefactoredGroup\AutoFflCheckoutMultiShipping\Block\Checkout\Dealers
 */
?>
<div data-mage-init='
    { "Magento_Ui/js/core/app":
        {
        "components":
            { "fflDealersPopupComponent" :
                {
                    "component": "RefactoredGroup_AutoFflCore/js/cart/dealers-popup",
                    "config": <?= $block->getJsonConfig() ?>
                }
            }
         }
      }
' data-bind="{scope:'fflDealersPopupComponent'}">
<!-- ko template: getTemplate() --><!-- /ko -->
</div>
