<?php
/**
 * Copyright © Refactored Group (https://www.refactored.group)
 * @copyright Copyright © 2022. All rights reserved.
 */
/**
 * Hide "Change" address links if a FFL item is in the cart
 *
 * @var $block \RefactoredGroup\AutoFflCheckoutMultiShipping\Block\Checkout\Ffl
 */
?>
<?php if ($block->isFfl()) : ?>
<style>
    .box-shipping-address .action.edit {
        display: none;
    }
</style>
<?php endif; ?>
