<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

?>
<a class="action multicheckout"
    href="<?= $block->escapeUrl($block->getCheckoutUrl()) ?>"
    data-mage-init='{
        "RefactoredGroup_AutoFflCheckoutMultiShipping/js/checkout/proceed-to-checkout-multiple-addresses": {}
    }'
>
    <span><?= $block->escapeHtml(__('Check Out with Multiple Addresses')) ?></span>
</a>
