name: Run script on SSH server

on:
  push:
    branches:
      - am/test

jobs:
  build:
    runs-on: ubuntu-latest
    environment: 'Andresa Test'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Connect to VPN
        run: |
          echo "${{ secrets.OPENVPN_CONFIG }}" | base64 -d > config.ovpn
          docker run -v $PWD:/vpn -d --cap-add=NET_ADMIN --device /dev/net/tun --name vpn dperson/openvpn-client -f "" -r 192.168.1.0/24
          echo "VPN connection successful"

      - name: Execute commands over ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            touch imconnected
